export const SET_CURRENCY = "SET_CURRENCY";
export const SET_LANGUAGE = "SET_LANGUAGE";


export const INIT_GOODS_LIST = "INIT_GOODS_LIST";
export const APPEND_TO_GOODS_LIST = "APPEND_TO_GOODS_LIST";
export const PREPEND_TO_GOODS_LIST = "PREPEND_TO_GOODS_LIST";

export const SHOW_SIDE_BAR = "SHOW_SIDE_BAR";
export const HIDE_SIDE_BAR = "HIDE_SIDE_BAR";
