export const SET_CURRENCY = 'SET_CURRENCY';
export const SET_LANGUAGE = 'SET_LANGUAGE';

export const INIT_GOODS_LIST = 'INIT_GOODS_LIST';
export const APPEND_TO_GOODS_LIST = 'APPEND_TO_GOODS_LIST';
export const PREPEND_TO_GOODS_LIST = 'PREPEND_TO_GOODS_LIST';

export const SHOW_SIDE = 'SHOW_SIDE';
export const HIDE_SIDE = 'HIDE_SIDE';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const SET_CUSTOMER = 'SET_CUSTOMER';


export const SET_CART_STATUS = 'SET_CART_STATUS';
export const SET_CART_LIST = 'SET_CART_LIST';
export const SET_CART_COUNT = 'SET_CART_COUNT';
export const ADD_GOODS_TO_CART = 'ADD_GOODS_TO_CART';
export const REMOVE_GOODS_FROM_CART = 'REMOVE_GOODS_FROM_CART';


